---
kind: pipeline
type: kubernetes
name: pgbouncer

platform:
  os: linux
  arch: aarch64

trigger:
  branches:
    - master
  event:
    - push

steps:
  - name: docker
    image: plugins/docker
    settings:
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: zebardy/pgbouncer
      dockerfile: Dockerfile
